[pytest]
asyncio_mode = auto
testpaths = app/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

[coverage:run]
source = app
omit = 
    app/tests/*
    */migrations/*

[coverage:report]
fail_under = 95
show_missing = True
